apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-h51w
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0047-tenant/ci1t-830-0047-app/devfile-sample-h51w@sha256:6d87de0ca4d3eb1473197cf12267ec59eb227785de4c6acf24f84bd33d398804
        name: my-nodejs
        resources: {}
status: {}
